### ISSUE TITLE
Submittion #26 (C++) :: Runtime Error

### ISSUE THREAD

**Issue by hamed-zamani** [amir-s/mithra_bugs#1]
<hr />

**Submitions ID**: `26`
**Problem**: `A+B`
**Judge Result**: `Runtime Error` - time: `0ms`, memory: `2024KB`
**Language**: C++ `cpp:5.4.0`

**Code**:
```
#include <iostream>
using namespace std;

int main () {
  int a, b;
  while (cin >> a >> b){
      cout << a+b << endl;
      cerr << "222";
  } 
  return 0;
}

```

**Comment by amir-s** [comment]
`C` and `C++` print errors in the `stderr`. So, if there's anything in the `stderr`, it should be counted as `runtime error`, otherwise a lot of other `runtime error`s wouldn't get caught.
