### ISSUE TITLE
Submittion #70 (C++) :: Runtime Error

### ISSUE THREAD

**Issue by saeedodak** [amir-s/mithra_bugs#2]
<hr />

**Submitions ID**: `70`
**Problem**: `A+B`
**Judge Result**: `Runtime Error` - time: `4ms`, memory: `2024KB`
**Language**: C++ `cpp:5.4.0`

**Code**:
```
#include <iostream>
using namespace std;

int main () {
  int t = clock();
  int a, b;
  while (cin >> a >> b) cout << a-b << endl;
  return 0;
}

```

**Comment by amir-s** [comment]
Judge reports a `runtime error` because `clock()` uses `SYS_clock_gettime` system call.

I'm not sure if this is something that can be used to abuse the judge. If it's safe, we can just whitelist this system call.

What is the use case exactly for someone to use `clock()` in a ACM contest?

**Comment by saeedodak** [comment]
[problem A](http://sharecode.io/contests/problem/61839769/A) in last online contest of Tehran site (15th Iran Nationwide Internet Contest), at first sight, I couldn't prove that all numbers will be equal so I divide time limit between test cases and use `clock()` to handle impossible cases. You can see our team first submission for this problem. [our_team](http://sharecode.io/users/profile/8704).
This function will be useful for solving randomization tasks like this [task](http://codeforces.com/contest/364/problem/D) which is discussed in this [blog](http://codeforces.com/blog/entry/51244) (there are lots of such tasks or at least someone may solve a task with approximate way)

**Comment by amir-s** [comment]
Thanks @saeedodak 
It should be fixed now. Please give it another!
